apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: better-city
build:
  tagPolicy:
    sha256: {}
  local:
    push: false
    useDockerCLI: true
  artifacts:
    - image: api-gateway
      context: services/api-gateway
      jib: {
        args: [
          '-Djib.to.image=api-gateway',
          '-Djib.container.environment=SPRING_PROFILES_ACTIVE=development',
          '-DskipTests=true'
        ]
      }
    - image: user-service
      context: services/user-service
      jib: {
        args: [
          '-Djib.to.image=user-service',
          '-Djib.container.environment=SPRING_PROFILES_ACTIVE=development',
          '-DskipTests=true'
        ]
      }
    - image: notification-service
      context: services/notification-service
      jib: {
        args: [
          '-Djib.to.image=notification-service',
          '-Djib.container.environment=SPRING_PROFILES_ACTIVE=development',
          '-DskipTests=true'
        ]
      }
    - image: issue-service
      context: services/issue-service
      jib: {
        args: [
          '-Djib.to.image=issue-service',
          '-Djib.container.environment=SPRING_PROFILES_ACTIVE=development',
          '-DskipTests=true'
        ]
      }
deploy:
  kubectl:
    manifests:
      - k8s/dev/00-database-namespace.yaml
      - k8s/dev/00-kafka-namespace.yaml
      - k8s/dev/20-gc-secret.yaml
      - k8s/dev/20-issue-service-db-credentials-db.yaml
      - k8s/dev/20-issue-service-db-credentials.yaml
      - k8s/dev/20-notification-service-db-credentials-db.yaml
      - k8s/dev/20-notification-service-db-credentials.yaml
      - k8s/dev/30-issue-service-db-deployment.yaml
      - k8s/dev/30-kafka-broker-deployment.yaml
      - k8s/dev/30-notification-service-db-deployment.yaml
      - k8s/dev/30-zookeeper-deployment.yaml
      - k8s/dev/40-issue-service-db-service.yaml
      - k8s/dev/40-kafka-broker-service.yaml
      - k8s/dev/40-notification-service-db-service.yaml
      - k8s/dev/40-zookeeper-service.yaml

      # Services
      - services/api-gateway/k8s/dev/*.yaml
      - services/user-service/k8s/dev/*.yaml
      - services/notification-service/k8s/dev/*.yaml
      - services/issue-service/k8s/dev/*.yaml