apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: better-city
build:
  tagPolicy:
    sha256: {}
  local:
    push: false
    useDockerCLI: true
  artifacts:
    - image: api-gateway
      context: services/api-gateway
      jib: {
        args: [
          '-Djib.to.image=api-gateway',
          '-Djib.container.environment=SPRING_PROFILES_ACTIVE=development',
          '-DskipTests=true'
        ]
      }
    - image: user-service
      context: services/user-service
      jib: {
        args: [
          '-Djib.to.image=user-service',
          '-Djib.container.environment=SPRING_PROFILES_ACTIVE=development',
          '-DskipTests=true'
        ]
      }
    - image: notification-service
      context: services/notification-service
      jib: {
        args: [
          '-Djib.to.image=notification-service',
          '-Djib.container.environment=SPRING_PROFILES_ACTIVE=development',
          '-DskipTests=true'
        ]
      }
    - image: issue-service
      context: services/issue-service
      jib: {
        args: [
          '-Djib.to.image=issue-service',
          '-Djib.container.environment=SPRING_PROFILES_ACTIVE=development',
          '-DskipTests=true'
        ]
      }
deploy:
  kubectl:
    manifests:
#      - k8s/dev/**/*.yaml
      # Databases
      - k8s/dev/0/00-database-namespace.yaml

      # Issue Service Database
      - k8s/dev/3/00-issue-service-db-credentials-db.yaml
      - k8s/dev/4/00-issue-service-db-deployment.yaml
      - k8s/dev/5/00-issue-service-db-service.yaml

      # Notification Service Database
      - k8s/dev/3/00-notification-service-db-credentials-db.yaml
      - k8s/dev/4/00-notification-service-db-deployment.yaml
      - k8s/dev/5/00-notification-service-db-service.yaml

      # kafka
      - k8s/dev/0/00-kafka-namespace.yaml
      - k8s/dev/4/00-zookeeper-deployment.yaml
      - k8s/dev/5/00-zookeeper-service.yaml
      - k8s/dev/4/10-kafka-broker-deployment.yaml
      - k8s/dev/5/10-kafka-broker-service.yaml

      # Services
      - k8s/dev/3/00-gc-secret.yaml

      # Api Gateway
      - k8s/dev/4/20-api-gateway-deployment.yaml
      - k8s/dev/5/20-api-gateway-service.yaml

      # Issue Service
      - k8s/dev/3/00-issue-service-db-credentials.yaml
      - k8s/dev/4/20-issue-service-deployment.yaml
      - k8s/dev/5/20-issue-service-service.yaml

      # Notification Service
      - k8s/dev/3/00-notification-service-db-credentials.yaml
      - k8s/dev/4/20-notification-service-deployment.yaml
      - k8s/dev/5/20-notification-service-service.yaml

      # User Service
      - k8s/dev/4/20-user-service-deployment.yaml
      - k8s/dev/5/20-user-service-service.yaml