apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: department-service-db
  name: department-service-db
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-service-db
  template:
    metadata:
      labels:
        app: department-service-db
    spec:
      containers:
        - name: department-service-db
          image: postgres:11.22-bullseye
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: department-service-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: department-service-db-credentials-db
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: department-service-db-credentials-db
                  key: password